SELECT F.PRODUCT_ID, F.PRODUCT_NAME, SUM(AMOUNT) * F.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT F JOIN FOOD_ORDER O
ON F.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY F.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID